Update run

diff --git a/.sti/bin/run b/.sti/bin/run
--- a/.sti/bin/run
+++ b/.sti/bin/run
@@ -7,5 +7,19 @@
 # For more information see the documentation:
 #	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
 #
+
+# Fail on a single failed command
+set -eo pipefail
+
+DIR=${DEPLOY_DIR:-/deployments}
+echo "Checking *.war in $DIR"
+if [ -d $DIR ]; then
+  for i in $DIR/*.war; do
+     file=$(basename $i)
+     echo "Linking $i --> /opt/jetty/webapps/$file"
+     ln -s $i /opt/jetty/webapps/$file
+  done
+fi
+
 export JAVA_OPTIONS="$JAVA_OPTIONS $(/opt/run-java.sh options) -Djava.security.egd=file:/dev/./urandom"
 exec java -Djava.io.tmpdir=/tmp/jetty $JAVA_OPTIONS -jar /usr/local/jetty/start.jar
